version: '2'

volumes:
  build:
    driver: local
  cache:
    external: true

services:
  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile  
    volumes:
      - cache:/cache
      - build:/build
    links:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.base
      BSRS_DB_CI_USER: bsdev
      BSRS_DB_CI_PASSWORD: tango
      TEST_OUTPUT_DIR: /reports
      DATABASE_HOST: postgres

  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  agent:
    image: snewcomer/ansible
    links:
      - postgres
    environment:
      PROBE_HOST: "postgres"
      PROBE_PORT: "5432"
    command: ["probe.yml"]

  postgres:
    build:
      context: ../../
      dockerfile: Dockerfile-psql
    environment:
      POSTGRES_PASSWORD: tango
      POSTGRES_USER: bsdev
      POSTGRES_DB: ci
    # ports:
    #   - "5433:5432"
