# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-02 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
