version: '2'

volumes:
  webroot:
    driver: local

services:
  app:
    build: 
      context: ../../
      dockerfile: docker/release/Dockerfile
    links:
      - postgres
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings.release
      BSRS_DB_CI_USER: dev
      BSRS_DB_CI_PASSWORD: puekey
      TEST_OUTPUT_DIR: /reports
      DATABASE_HOST: postgres
    volumes:
      - webroot:/var/www/backend
    command:
      - uwsgi
      - "--socket /var/www/backend/backend.sock"
      - "--chmod-socket=666"
      - "--module backend.wsgi"
      - "--master"
      - "--die-on-term"

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    links:
      - app
    ports:
      - "8000:8000"
    volumes:
      - webroot:/var/www/backend

  postgres:
    build:
      context: ../../
      dockerfile: Dockerfile-psql
    environment:
      POSTGRES_PASSWORD: tango
      POSTGRES_USER: bsdev
      POSTGRES_DB: ci
    # env_file:
    #   - ../../env/app.${APP_ENV}.env
    # ports:
    #   - "5434:5432"

  agent:
    image: snewcomer/ansible
    links:
      - postgres
    environment:
      PROBE_HOST: "postgres"
      PROBE_PORT: "5432"
    command: ["probe.yml"]
